name: "Docs - Main - Deploy"

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-deploy-main.yml'
  workflow_dispatch:

# Ensure documentation workflows run sequentially
concurrency:
  group: "docs-deployment"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: './docs'

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: |
          cd docs
          bundle exec jekyll build --baseurl "/GitHubStagingPages"
        env:
          JEKYLL_ENV: production

      - name: Upload main site artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-site
          path: ./docs/_site
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download main site artifact
        uses: actions/download-artifact@v4
        with:
          name: main-site
          path: /tmp/main-temp

      - name: Setup main site content
        run: |
          find . -maxdepth 1 \
              -not -name 'staging' \
              -not -name '.git' \
              -not -name '.' \
              -not -name '..' \
            -exec rm -rf {} \;
          cp -r /tmp/main-temp/* .
          rm -rf /tmp/main-temp

      - name: Commit and push main site content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Deploy main documentation from commit ${{ github.sha }}"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
